language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.1
  - 7.2
matrix:
    allow_failures:
      - python: 5.3
      - python: 5.5
install:
  - composer install --no-dev --quiet
script: phpunit -c phpunit.xml
